name: map4d_services
description: A flutter plugin for integrating Map4D Services in iOS and Android applications.
version: 1.2.0
homepage: https://map4d.vn
repository: https://github.com/map4d/map4d-services-flutter
issue_tracker: https://github.com/map4d/map4d-services-flutter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: vn.map4d.services.map4d_services
        pluginClass: Map4dServicesPlugin
      ios:
        pluginClass: Map4dServicesPlugin
